# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Geeks in HK"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Since 2008 from Hong Kong - migrated from geeksinhk.wordpress.com"

# Tagline near the site title
tagline: "A bunch of notes."

# The subpath of your site, e.g. /blog, for generating urls
baseurl: 

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://scottietse.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: wishlog

# Author information - author info at the bottom of the post
author_name: "Scott Tse"
author_bio: ""
author_url:  "https://scottietse.com"
author_location: "Hong Kong, China"
author_image: images/banner.jpg

# Sidebar Add banner
banner_url: "https://scottietse.com"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
mailchimp_url: "none"

# Social links in the site footer
twitter_username: "wishlog"
#googleplus_username: "+wishlog"
github_username: "wishlog"
#codepen_username: ""
#dribbble_uername: ""
#medium_username: "@"
instagram_username: "wishlog"
#pinterest_username: ""
linkedin_username: "scottietse"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
